apiVersion: v1
kind: Pod
metadata:
  name: kafkacat
spec:
  containers:
  - name: kafkacat
    image: confluentinc/cp-kcat:7.5.1
    command: ["sh", "-c", "exec tail -f /dev/null"]
    volumeMounts:
    - name: my-user
      mountPath: "/my-user"
      readOnly: true
    - name: config-volume
      mountPath: /home/appuser/.config
  volumes:
  - name: my-user
    secret:
      secretName: my-user
  - name: config-volume
    configMap:
      name: kcat-config
